# file đã được lược bớt các phần mặc định được dánh dấu #, chỉ còn phần không đánh dấu #
# các thành phần cần chỉnh sửa (bỏ dấu #) bao gồm `ListenPort`, `DBHost`, `DBName`, `DBUser`
# điền mật khẩu đã tạo của Database tại `DBPassword` để Zabbix Server kết nối Database
ListenPort=10051
LogFile=/var/log/zabbix/zabbix_server.log
LogFileSize=0
PidFile=/run/zabbix/zabbix_server.pid
SocketDir=/run/zabbix
DBHost=localhost
DBName=zabbix
DBUser=zabbix
DBPassword=password_da_tao
SNMPTrapperFile=/var/log/snmptrap/snmptrap.log
Timeout=4
FpingLocation=/usr/bin/fping
Fping6Location=/usr/bin/fping6
LogSlowQueries=3000
StatsAllowedIP=127.0.0.1
EnableGlobalScripts=0
Include=/etc/zabbix/zabbix_server.d/*.conf
